### ISSUE TITLE
Linux troubles

### ISSUE THREAD

**Issue by Farkoth** [anegostudios/vsmodelcreator#94]
Due [to](https://github.com/anegostudios/vsmodelcreator/issues/93) doesnt works for me, and #91 didnt helps too, what else should i do? VSMC still wants in .swt directory .so files. Both on java8 and java11.

**Comment by Th3Dilli** [comment]
Hey sorry that there was so long no response nor a working linux version

this should now be solved and with next release we will have dual releases to address this

the issue was that the swt.jar for linux and windows have their own natives and this is not handled at runtime and needs to be in the classpath at start

to fix it temporarily you can copy the `swt-gtk4.jar` from `natives/linux` to `vsmodelcreator_lib/swt.jar` then it should work just fine

**Comment by Farkoth** [comment]
Thanks! I'll just better wait next release, for now using VS Model Creator for 21 may 2021 and its works
